# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(609, 386)
        self.pushButton_download = QtWidgets.QPushButton(Form)
        self.pushButton_download.setEnabled(False)
        self.pushButton_download.setGeometry(QtCore.QRect(260, 290, 131, 61))
        self.pushButton_download.setObjectName("pushButton_download")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 16))
        self.label.setObjectName("label")
        self.lineEdit_url = QtWidgets.QLineEdit(Form)
        self.lineEdit_url.setGeometry(QtCore.QRect(30, 40, 541, 31))
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 131, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_filename = QtWidgets.QLineEdit(Form)
        self.lineEdit_filename.setGeometry(QtCore.QRect(30, 120, 541, 31))
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 131, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_path = QtWidgets.QLineEdit(Form)
        self.lineEdit_path.setGeometry(QtCore.QRect(30, 200, 541, 31))
        self.lineEdit_path.setObjectName("lineEdit_path")
        # self.lineEdit_path.setText("G:/Download")
        self.pushButton_choose = QtWidgets.QPushButton(Form)
        self.pushButton_choose.setGeometry(QtCore.QRect(480, 170, 93, 28))
        self.pushButton_choose.setObjectName("pushButton_choose")
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setGeometry(QtCore.QRect(430, 290, 131, 61))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_state = QtWidgets.QLabel(Form)
        self.label_state.setGeometry(QtCore.QRect(30, 260, 141, 16))
        self.label_state.setText("")
        self.label_state.setObjectName("label_state")
        print("parent setting")

        self.retranslateUi(Form)
        self.pushButton_choose.clicked.connect(self.choosePath) # type: ignore
        self.pushButton_download.clicked.connect(self.startDownload) # type: ignore
        self.pushButton_exit.clicked.connect(self.exitApp) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_download.setText(_translate("Form", "下载"))
        self.label.setText(_translate("Form", "输入m3u8地址:"))
        self.label_2.setText(_translate("Form", "输入文件名(.mp4):"))
        self.label_3.setText(_translate("Form", "下载路径:"))
        self.pushButton_choose.setText(_translate("Form", "选择"))
        self.pushButton_exit.setText(_translate("Form", "退出"))
